# Generated by Django 5.0.7 on 2025-10-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='sucursales_autorizadas',
            field=models.ManyToManyField(blank=True, help_text='Sucursales en las que el usuario puede abrir caja (solo para usuarios no administradores).', related_name='vendedores_autorizados', to='sucursales.sucursal'),
        ),
    ]
