# Generated by Django 5.0.7 on 2025-10-08 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('users', '0002_vendedor_sucursales_autorizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='sucursales_autorizadas',
            field=models.ManyToManyField(blank=True, help_text='Sucursales en las que el usuario puede abrir caja.', related_name='vendedores_autorizados', to='sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
