# Generated by Django 5.0.7 on 2025-10-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='efectivo_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_ventas_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_ventas_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_ventas_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='ventas_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='vuelto_entregado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
