# Generated by Django 5.0.7 on 2025-10-12 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_aperturacierrecaja_efectivo_final_and_more'),
        ('sucursales', '0002_sucursal_low_stock_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='apertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
