# Generated by Django 5.0.7 on 2026-02-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_alter_venta_forma_pago_devolucion_devoluciondetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_nota_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='nota_credito_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='cashier.notacredito'),
        ),
    ]
