# Generated by Django 5.0.7 on 2026-03-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_venta_store_credit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('nota_credito', 'Nota de crédito'), ('mixto', 'Mixto')], default='efectivo', max_length=20),
        ),
        migrations.CreateModel(
            name='VentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cashier.notacredito')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cashier.venta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ventapago',
            constraint=models.UniqueConstraint(condition=models.Q(('metodo', 'nota_credito')), fields=('venta',), name='unique_nota_credito_pago_per_venta'),
        ),
        migrations.AddConstraint(
            model_name='ventapago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gte', 0)), name='venta_pago_monto_non_negative'),
        ),
    ]
