# Generated by Django 5.0.7 on 2025-10-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0, help_text='0 usa el umbral global'),
        ),
    ]
