# Generated by Django 5.0.7 on 2026-06-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
