# Generated by Django 5.0.7 on 2026-06-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_alter_sucursal_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
