# Generated by Django 5.0.7 on 2025-10-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursales_autorizadas',
            field=models.ManyToManyField(blank=True, help_text='Sucursales en las que el usuario puede abrir cajas (solo para usuarios no administradores).', related_name='usuarios_autorizados', to='reports.sucursal'),
        ),
    ]
