# Generated by Django 5.0.7 on 2026-05-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_sucursales_autorizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_products',
            field=models.BooleanField(default=False, help_text='Puede agregar productos a sucursales seleccionadas'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_products',
            field=models.BooleanField(default=False, help_text='Puede editar valores y atributos de productos'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_analytics',
            field=models.BooleanField(default=False, help_text='Puede ver los reportes y analíticas del sistema'),
        ),
    ]
