"""
Django settings for MOVOS project.
Generated by 'django-admin startproject' using Django 5.0.7.
This settings module is environment-driven for easy Docker/production use.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.environ.get(name)
    if raw is None:
        return default
    items = [x.strip() for x in str(raw).split(',')]
    return [x for x in items if x]

# Security & environment
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-5o(k+1^on5m8ca--ieap-e%wqn6(#vnouc8%i3!tbt-((1%hh7')

DEBUG = _env_bool('DEBUG', False)

# Enable React UI (Vite build) in production when available.
# - Dev uses Vite dev server when DEBUG=True (via local_settings.py).
# - Prod/OrangePi: set REACT_UI_ENABLED=1 and run the Vite build.
REACT_UI_ENABLED = os.environ.get('REACT_UI_ENABLED', '').lower() in ('1', 'true', 'yes', 'on')

# Optional: where the Vite dev server runs in development.
VITE_DEV_SERVER_URL = os.environ.get('VITE_DEV_SERVER_URL', 'http://localhost:5173')

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    [
        'localhost',
        '127.0.0.1',
        'rochart-multiservicios.cl',
        'www.rochart-multiservicios.cl',
        '.rochart-multiservicios.cl',
    ],
)

CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'http://localhost:8000',
        'https://rochart-multiservicios.cl',
        'https://www.rochart-multiservicios.cl',
    ],
)

# Optional cookie domain overrides (useful if you serve both www and non-www)
_SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN')
if _SESSION_COOKIE_DOMAIN:
    SESSION_COOKIE_DOMAIN = _SESSION_COOKIE_DOMAIN

_CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN')
if _CSRF_COOKIE_DOMAIN:
    CSRF_COOKIE_DOMAIN = _CSRF_COOKIE_DOMAIN

# Security/session toggles tuned by environment (important behind proxies).
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Strict')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Strict')
SESSION_SAVE_EVERY_REQUEST = _env_bool('SESSION_SAVE_EVERY_REQUEST', True)

# Respect reverse proxy HTTPS headers (Nginx/Cloudflare) to prevent scheme flips.
if _env_bool('USE_X_FORWARDED_PROTO', True):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = _env_bool('USE_X_FORWARDED_HOST', True)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0') or 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'same-origin')

# Optional canonical host redirect (www vs non-www)
CANONICAL_HOST = os.environ.get('CANONICAL_HOST')
CANONICAL_HOST_PERMANENT = os.environ.get('CANONICAL_HOST_PERMANENT', '')


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cashier',
    'products',
    'users.apps.UsersConfig',
    'reports',
    'auth_app',
    'django.contrib.humanize',
    'sucursales',
]

AUTH_USER_MODEL = 'auth_app.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'users.middleware.CanonicalHostMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.AutoLogoutMiddleware',
    'users.middleware.RedirectOn404Middleware',
]

ROOT_URLCONF = 'MOVOS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                # Global template filters (so templates can use |clp without {% load %}).
                'cashier.templatetags.money_filters',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MOVOS.wsgi.application'

# Database
DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite')
if DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'movos'),
            'USER': os.environ.get('POSTGRES_USER', 'movos'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'movos'),
            'HOST': os.environ.get('POSTGRES_HOST', 'db'),
            'PORT': int(os.environ.get('POSTGRES_PORT', '5432')),
        }
    }
    # Optional SSL (e.g., Neon, some managed Postgres)
    if os.environ.get('POSTGRES_SSL', 'false').lower() in ('1', 'true', 'yes'):
        DATABASES['default']['OPTIONS'] = { 'sslmode': 'require' }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'es-cl')
TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Santiago')
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
LOGIN_URL = '/login/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Session version: bump this value (via env or local_settings.py) to immediately
# invalidate all existing sessions across all browsers without requiring clients
# to clear cookies.  AutoLogoutMiddleware checks this on every authenticated request.
SESSION_VERSION = os.environ.get('SESSION_VERSION', '1')

# Session lifetime: 8 hours of inactivity max for a retail POS environment.
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', str(8 * 60 * 60)))

# Allow secret-key rotation without forcing all users to re-login immediately.
SECRET_KEY_FALLBACKS = _env_list('SECRET_KEY_FALLBACKS', [])

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Umbral global para marcar stock como "bajo"
LOW_STOCK_THRESHOLD = int(os.environ.get('LOW_STOCK_THRESHOLD', '2'))

# Auto logout delay (inactivity)
# If unset, auto-logout is disabled (no disconnection by inactivity).
_AUTO_LOGOUT_DELAY_RAW = os.environ.get('AUTO_LOGOUT_DELAY')
if _AUTO_LOGOUT_DELAY_RAW is None or str(_AUTO_LOGOUT_DELAY_RAW).strip() == '':
    AUTO_LOGOUT_DELAY = None
else:
    AUTO_LOGOUT_DELAY = int(_AUTO_LOGOUT_DELAY_RAW)

# Local overrides (not committed): create MOVOS/local_settings.py to override
# DATABASES or other settings for local development. This file is imported if
# present to avoid changing the main settings for production/docker.
try:
    from .local_settings import *  # noqa: F401,F403
except ImportError:
    pass
except Exception as _ls_exc:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(f"Error en local_settings.py: {_ls_exc}") from _ls_exc

# En producción rechazar el SECRET_KEY inseguro por defecto.
if not DEBUG and 'django-insecure' in SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "SECRET_KEY insegura detectada. Define la variable de entorno SECRET_KEY "
        "con un valor aleatorio largo antes de ejecutar en producción."
    )

# In local development, avoid cached template loader so template edits are reflected
# immediately on refresh. Cached templates are useful in production but confusing
# while iterating on UI.
if DEBUG:
    try:
        TEMPLATES[0].setdefault('OPTIONS', {})
        TEMPLATES[0]['APP_DIRS'] = False
        TEMPLATES[0]['OPTIONS']['loaders'] = [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]
    except Exception:
        # If TEMPLATES isn't in expected shape, don't crash settings import.
        pass