# Generated by Django 5.0.7 on 2025-06-20 23:01

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_permitir_venta_sin_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='codigo_alternativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CÓDIGO2'),
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='FECHA DE INGRESO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_compra_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='COSTO C/IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VENDEDOR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='CANTIDAD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='CÓDIGO DE BARRAS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPCIÓN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='permitir_venta_sin_stock',
            field=models.BooleanField(default=False, verbose_name='PERMITIR VENTA SIN STOCK'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PRECIO COMPRA SIN IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='$ VTA C/IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producto_id',
            field=models.CharField(default='default_id', max_length=20, unique=True, verbose_name='CÓDIGO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='STOCK'),
        ),
    ]
