# Generated by Django 5.0.7 on 2025-06-21 00:02

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_codigo_alternativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precio_compra',
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación del Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='product',
            name='margen_dinero_importado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Margen $'),
        ),
        migrations.AddField(
            model_name='product',
            name='margen_porcentaje_importado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margen'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_neto_importado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='$ Neto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='CANTIDAD EN ALMACEN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_alternativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CODIGO2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CÓDIGO DE BARRAS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPCION'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_compra_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Costo c/IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='$ Vta c/IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producto_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='CODIGO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='STOCK ACTUAL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VENDEDOR'),
        ),
    ]
