# Generated by Django 5.0.7 on 2025-06-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_remove_product_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NOMBRE DEL PRODUCTO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='CANTIDAD INICIAL'),
        ),
    ]
