# Generated by Django 5.0.7 on 2025-09-23 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_nombre_alter_product_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_alternativo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Alternativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_dinero_importado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Margen en Dinero Importado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_porcentaje_importado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Margen (%) Importado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='permitir_venta_sin_stock',
            field=models.BooleanField(default=False, verbose_name='Permitir Venta sin Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_compra_con_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de Compra c/IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_neto_importado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Neto Importado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de Venta c/IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producto_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código (Producto ID)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendedor'),
        ),
    ]
