# Generated by Django 5.0.7 on 2025-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options_remove_product_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_ingreso_producto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor'),
        ),
    ]
