# Generated by Django 5.0.7 on 2025-09-23 17:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='iva_porcentaje',
        ),
        migrations.RemoveField(
            model_name='product',
            name='margen_dinero_importado',
        ),
        migrations.RemoveField(
            model_name='product',
            name='margen_porcentaje_importado',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precio_compra_con_iva',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precio_neto_importado',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='product',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_alternativo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producto_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código 1'),
        ),
    ]
