# Generated by Django 5.0.7 on 2025-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='permitir_venta_sin_stock',
            field=models.BooleanField(default=True, verbose_name='Permitir Venta sin Stock'),
        ),
    ]
