# Generated by Django 5.0.7 on 2025-10-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_cantidad_alter_product_stock'),
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='reports.sucursal'),
        ),
    ]
