# Generated by Django 5.0.7 on 2025-10-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_sucursal'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='sucursales.sucursal'),
        ),
    ]
