# Generated by Django 5.0.7 on 2026-05-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksucursal',
            name='permitir_venta_sin_stock',
            field=models.BooleanField(blank=True, help_text='Si es null, usa el valor del producto', null=True, verbose_name='Permitir Venta sin Stock'),
        ),
    ]
